<?php

	require_once("config.php");
	require_once("functions.php");
		//this is one of the main functions to be called by the main script. It gets the contact information according to parameters (email etc..)
	function createContact(array $params = array())
    {
		//the actual url for the contacts api endpoint
        /*$baseUrl = "https://api.constantcontact.com/v2/contacts";
		//uses the buildUrl function to construct full url with api key and parameters
		$getUrl = buildUrl($baseUrl, $params);*/
		$postUrl = buildUrl(contacts_base_url, $params, true);
		var_dump($params);
		echo $postUrl;
        //sends an actual request to the url above using specific method (get)...
		//   and using headers generated by getHeaders function (headers will contain the access token)
		//!! this is where actual api happens !!
		//result is saved in $response
		//!! this is where the TOKEN needs to be changed if necessary !!
		//$response = httpRequest($getUrl, "GET", getHeaders());
		//$body = json_decode($response["body"], true);
		//if (array_key_exists("results", $body)) {
		if (getContact($params["email"])) {
			//echo "contact exists<br><br>\n\n";

		outputToModal("addmodal", "Epic Fail!", "This contact already exists");
		} else {
			$arr = array("lists" => array(array("id" => "")),
						 "email_addresses" => array(array("email_address" => "")),
			             "first_name" => ""
			            );
			$arr["lists"][0]["id"] = $params["list_id"];
			$arr["email_addresses"][0]["email_address"] = $params["email"];
			$arr["first_name"] = $params["first_name"];
			
			$response = httpRequest($postUrl, "POST", getHeaders(), json_encode($arr));
        //echo 'great success: contact successfully added';
		
					echo "\n" . $response["info"]["http_code"];
			if ($response["info"]["http_code"] != 201) {
				outputToModal("addmodal", "Error!", "Something went wrong!");
			} else {
				outputToModal("addmodal", "Success!", "You have successfully added a contact");
			}
		}
        //var_dump($response);
		
		/*$body = json_decode($response["body"], true);
        //var_dump($body);
		for ($i = 0; $i < count($body["results"]); ++$i) {
			echo "id: " . $body["results"][$i]["id"] . "<br>\n";
			echo "first name: " . $body["results"][$i]["first_name"] . "<br>\n";
			echo "email: " . $body["results"][$i]["email_addresses"][0]["email_address"] . "<br>\n";
			echo "status: " . $body["results"][$i]["status"] . "<br>\n";
			echo "created date: " . $body["results"][$i]["created_date"] . "<br>\n";
			echo "<br>\n";
		}
		
		if (count($body["results"]) == 0) {
			echo "contact not found<br><br>\n\n";
		}
		
		echo "HTTP response code: " . $response["info"]["http_code"] . "<br>\n";
		//var_dump($response["info"]); */ //UNCOMMENT THIS BLOCK !!!

		/*$contacts = array();
        foreach ($body['results'] as $contact) {
            $contacts[] = Contact::create($contact);
        }
        return new ResultSet($contacts, $body['meta']);*/
    }
	
	createContact($_POST);
	